import { Email } from '../value-objects/email.value-object';

export class User {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly email: Email,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public isActive: boolean = true,
  ) {}

  deactivate(): void {
    this.isActive = false;
  }

  activate(): void {
    this.isActive = true;
  }

  static create(name: string, email: string): User {
    const emailVO = new Email(email);
    const now = new Date();

    return new User(
      '', // ID will be generated by the database
      name,
      emailVO,
      now,
      now,
      true,
    );
  }
}
